import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  EthersExtension,
  DynamicContextProvider,
  EthereumWalletConnectors,
} from "../lib/dynamic";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gnosis Dynamic App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DynamicContextProvider
        settings={{
          environmentId: "299c3720-c413-49cb-bc32-ab64b2244bc4",
          walletConnectors: [EthereumWalletConnectors],
          walletConnectorExtensions: [EthersExtension],
        }}
      >
        <body className={inter.className}>{children}</body>
      </DynamicContextProvider>
    </html>
  );
}
